routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('teams/export', 'Team@export')->name('teams.export');
Route::get('teams/exportxml', 'Team@exportxml')->name('teams.exportxml');
Route::get('teams/downloadxml/{filename}', 'Team@downloadxml')->name('teams.downloadxml');

Route::get('/', 'Team@index');
Route::resource('teams', 'Team');
Route::resource('players', 'Player');

app/Player.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Player extends Model
{
    protected $fillable = ['name', 'shirt_number', 'team_id'];

    public function Team(){
        return $this->belongsTo(Team::class);
    }

    public function search($filter = NULL){
        return $this
        ->when($filter['team_id'], function($query, $termo){
            $query->where('team_id', $termo);
        })
        ->get();
    }
}

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    protected $fillable = ['name', 'city'];

    public function players(){
        return $this->hasMany(Player::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Player.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class Player extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->has('team')){
            $filter = array(
                'team_id' => $request->input('team')
            );
            $players = new \App\Player();
            $players = $players->search($filter);
        }else{
            $players = \App\Player::all();
        }

        return view('players', compact('players'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $teams = \App\Team::all();
        return view('player-register', compact('player', 'teams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = $request->validate([
            'name' => 'required',
            'shirt_number' => 'required',
            'team_id' => 'required'
        ]);
        $player = \App\Player::create($validation);
        return redirect('/players')->with('success', 'Jogador Adicionado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $player = \App\Player::findOrFail($id);
        $teams = \App\Team::all();

        return view('player-register', compact('player', 'teams'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = $request->validate([
            'name' => 'required',
            'shirt_number' => 'required',
            'team_id' => 'required'
        ]);

        \App\Player::whereId($id)->update($validation);

        return redirect('/players')->with('success', 'Jogador Salvo');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $player = \App\Player::findOrFail($id);
        $player->delete();

        return redirect('/players')->with('success', 'Jogador deletado da sua base');
    }
}

app/Http/Controllers/Team.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Storage;

class Team extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teams = \App\Team::all();
        return view('teams', compact('teams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('team-register');
    }

    /**
     * Export teams data to a csv file.
     *
     * @return \Illuminate\Http\Response
     */
    public function export()
    {
        return Excel::download(new \App\Exports\TeamsExport, 'times.csv');
    }

    /**
     * Export teams data to a xml file.
     *
     * @return \Illuminate\Http\Response
     */
    public function exportxml()
    {
        set_time_limit(0);
        $teams = new \App\Team();
        $teams = $teams->with('players')->get();
        $x=new \XMLWriter();
        $x->openMemory();
        $x->startDocument('1.0','UTF-8');
        $x->startElement('teams');
        foreach ($teams as $team) {

            $x->startElement('team');
            $x->writeAttribute('name',$team['name']);

            foreach ($team['players'] as $player) {

                $x->startElement('player');
                $x->writeAttribute('name',$player['name']);
                $x->writeAttribute('shirt_number',$player['shirt_number']);
                $x->endElement(); // player
            } // foreach $players

            $x->endElement(); // team
        } // foreach $teams

        $x->endElement(); // teams
        $x->endDocument();
        $xml = $x->outputMemory();

        \Storage::disk('local')->put('teams.xml', $xml);
        return response()->json(['success' => 'success', 'filename'=>'teams.xml'], 200);
    }

    public function downloadxml($filename)
    {
        return \Storage::download($filename);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = $request->validate([
            'name' => 'required',
            'city' => 'required'
        ]);
        $team = \App\Team::create($validation);
        return redirect('/teams')->with('success', 'Time Adicionado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $team = \App\Team::findOrFail($id);
        return view('team-register', compact('team'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = $request->validate([
            'name' => 'required',
            'city' => 'required'
        ]);

        \App\Team::whereId($id)->update($validation);

        return redirect('/teams')->with('success', 'Time Salvo');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $team = \App\Team::findOrFail($id);
        $team->delete();

        return redirect('/teams')->with('success', 'Time deletado da sua base');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    @yield('css')
    <title>@yield('title') - Futebol</title>
</head>
<body>
        <div class="navigation">
            <nav>
                <a href="/" class="logo">Início</a>
                <a href="{{ route('teams.index') }}" class="btn btn-outline-light">Times</a>
                <a href="{{ route('players.index') }}" class="btn btn-outline-light">Jogadores</a>
                <div id="download-all" class="btn btn-outline-light">Exportar Tudo</div>
            </nav>
        </div>

        <div class="content">
            @yield('conteudo')
        </div>




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>

</body>
</html>

resources/views/player-register.blade.php
@section('title', 'Jogadores')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
@stop

@extends('layouts.app')

@section('conteudo')

    @if(session()->get('success'))
        <div class="message success">
        {{ session()->get('success') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="message error">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="topo">
        <h1>@if(isset($player)) Editar Jogador: {{ $player->name }}  @else Adicionar Jogador @endif</h1>
    </div>


    <form method="post" action="{{ (isset($player)) ? route('players.update', $player->id) : route('players.store') }}" class="card form shadow">
        @csrf
        @if(isset($player))
            @method('PATCH')
        @endif
        <input name="id" type="hidden" value="{{ (isset($player->id)) ? $player->id : '' }}">
        <div class="input-container">
          <input placeholder=" " id="iName" type="text" name="name" required value="{{ (isset($player->name)) ? $player->name : '' }}">
          <label for="iName">Nome do Jogador *</label>
        </div>
        <div class="input-container">
            <input placeholder=" " id="iShirtNumber" type="text" name="shirt_number" required value="{{ (isset($player->shirt_number)) ? $player->shirt_number : '' }}">
            <label for="iShirtNumber">Número da Camisa *</label>
        </div>
        <div class="input-container">
            <select class="form-control" id="team_id" name="team_id" required>
                @foreach($teams as $team)
                    <option {{ (isset($player) && $player->team_id == $team->id) ? 'selected' : '' }} value="{{ $team->id }}">{{ $team->name }}</option>
                @endforeach
            </select>
            <label for="team_id">Pertence ao Time *</label>
        </div>
        <div class="opcoes">
            <a href="javascript:history.back()" class="btn">Cancelar</a>
            <button type="submit" class="btn color">Salvar</button>
        </div>
      </form>

@endsection

resources/views/players.blade.php
@section('title', 'Jogadores')

@extends('layouts.app')

@section('conteudo')

    @if(session()->get('success'))
        <div class="message success">
        {{ session()->get('success') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="message error">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="topo">
        <h1>Jogadores</h1>
        <div class="opcoes-top">
            <a href="{{ route('players.create') }}" class="btn color"><span>+</span> Novo Jogador</a>
        </div>

    </div>


    <div class="players card-group">

        @if(isset($players) && count($players) > 0)

            @foreach($players as $player)

                <div class="card shadow">
                    <div class="card-image">
                        <h2 class="card-title">{{ $player->name }}</h2>
                        <p class="card-description">Camisa nº {{ $player->shirt_number }}</p>
                    </div>
                    <div class="opcoes">
                        <form action="{{ route('players.destroy' , $player->id)}}" method="POST">
                            <input name="_method" type="hidden" value="DELETE">
                            {{ csrf_field() }}

                            <button type="submit" class="btn">Excluir</button>
                        </form>
                        <a href="{{ route('players.edit', $player->id) }}" class="btn">Editar</a>
                    </div>
                </div>

            @endforeach

        @else

            <h2>Nada por aqui</h2>

        @endif

    </div>

@endsection

resources/views/team-register.blade.php
@section('title', 'Times')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
@stop

@extends('layouts.app')

@section('conteudo')

    @if(session()->get('success'))
        <div class="message success">
        {{ session()->get('success') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="message error">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="topo">
        <h1>@if(isset($team)) Editar time: {{ $team->name }}  @else Adicionar Time @endif</h1>
    </div>


    <form method="post" action="{{ (isset($team)) ? route('teams.update', $team->id) : route('teams.store') }}" class="card form shadow">
        @csrf
        @if(isset($team))
            @method('PATCH')
        @endif
        <input name="id" type="hidden" value="{{ (isset($team->id)) ? $team->id : '' }}">
        <div class="input-container">
          <input placeholder=" " id="iNome" type="text" name="name" required value="{{ (isset($team->name)) ? $team->name : '' }}">
          <label for="iNome">Nome do Time *</label>
        </div>
        <div class="input-container">
            <input placeholder=" " id="iCity" type="text" name="city" required value="{{ (isset($team->city)) ? $team->city : '' }}">
            <label for="iCity">Cidade *</label>
        </div>
        <div class="opcoes">
            <a href="javascript:history.back()" class="btn">Cancelar</a>
            <button type="submit" class="btn color">Salvar</button>
        </div>
      </form>

@endsection

resources/views/teams.blade.php
@section('title', 'Times')

@extends('layouts.app')

@section('conteudo')

    @if(session()->get('success'))
        <div class="message success">
        {{ session()->get('success') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="message error">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="topo">
        <h1>Times</h1>
        <div class="opcoes-top">
            <a href="{{ route('teams.export') }}" class="btn"><span>></span> Exportar CSV</a>
            <a href="{{ route('teams.create') }}" class="btn color"><span>+</span> Novo Time</a>
        </div>
    </div>


    <div class="teams card-group">

        @if(isset($teams) && count($teams) > 0)

            @foreach($teams as $team)

                <div class="card shadow">
                    <div class="card-image">
                        <h2 class="card-title">{{ $team->name }}</h2>
                        <p class="card-description">{{ $team->city }}</p>
                    </div>
                    <div class="opcoes">
                            <form action="{{ route('teams.destroy' , $team->id)}}" method="POST">
                                <input name="_method" type="hidden" value="DELETE">
                                {{ csrf_field() }}

                                <button type="submit" class="btn">Excluir</button>
                            </form>
                        <a href="{{ route('teams.edit', $team->id) }}" class="btn">Editar</a>
                        <a href="{{ route('players.index', ['team' => $team->id]) }}" class="btn">Ver Jogadores</a>
                    </div>
                </div>

            @endforeach

        @else

            <h2>Nada por aqui</h2>

        @endif

    </div>

@endsection